name: Laravel-Deploy

on:
  push:
    branches:
      - main

jobs:
  Laravel-Deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Copiar al directorio
        run: |
          sudo rsync -avz --delete \
          --exclude=.env \
          --exclude=storage \
          $GITHUB_WORKSPACE/ /var/www/api.timeboard.live/
      - name: Deploy
        working-directory: /var/www/api.timeboard.live
        run: |
          php artisan route:cache
          php artisan config:cache
