name: Laravel-Deploy

on:
  push:
    branches:
      - master

jobs:
  Laravel-Deploy:
    runs-on: self-hosted

    steps:
      # - name: Checkout code
      #   working-directory: /var/www/api.timeboard.live
      #   run: |
      #     git pull
      #     php artisan route:cache
      #     php artisan config:cache
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Copiar al directorio
        run: |
          sudo rsync -avz --delete \
          --exclude=.env \
          --exclude=storage \
          --exclude=vendor/ \
          --exclude=database/*.sqlite \
          $GITHUB_WORKSPACE/ /var/www/api.timeboard.live/
      - name: Aplicando comandos de Laravel
        working-directory: /var/www/api.timeboard.live
        run: |
          php artisan route:cache
          php artisan config:cache
      - name: Ajustar permisos
        run: |
          sudo chown -R www-data:www-data /var/www/api.timeboard.live/storage /var/www/api.timeboard.live/bootstrap/cache
          sudo chmod -R 775 /var/www/api.timeboard.live/storage /var/www/api.timeboard.live/bootstrap/cache
