name: Laravel-Deploy

on:
  push:
    branches:
      - main

jobs:
  Laravel-Deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        working-directory: /var/www/api.timeboard.live
        run: |
          git pull
          php artisan route:cache
          php artisan config:cache
